// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: kvs/v1/kvs.proto

package kvsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType describes what happened to a watched key.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_SET         EventType = 1
	EventType_EVENT_TYPE_DELETE      EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_SET",
		2: "EVENT_TYPE_DELETE",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_SET":         1,
		"EVENT_TYPE_DELETE":      2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_kvs_v1_kvs_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_kvs_v1_kvs_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{3}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{5}
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{6}
}

func (x *WatchRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type WatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=kvs.v1.EventType" json:"type,omitempty"`
	Key   string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Value is set for EVENT_TYPE_SET events and empty for deletes.
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{7}
}

func (x *WatchResponse) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_kvs_v1_kvs_proto protoreflect.FileDescriptor

const file_kvs_v1_kvs_proto_rawDesc = "" +
	"\n" +
	"\x10kvs/v1/kvs.proto\x12\x06kvs.v1\x1a\x1cgoogle/api/annotations.proto\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"4\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\r\n" +
	"\vSetResponse\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x10\n" +
	"\x0eDeleteResponse\" \n" +
	"\fWatchRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"^\n" +
	"\rWatchResponse\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.kvs.v1.EventTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value*R\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eEVENT_TYPE_SET\x10\x01\x12\x15\n" +
	"\x11EVENT_TYPE_DELETE\x10\x022\xbb\x02\n" +
	"\n" +
	"KVSService\x12D\n" +
	"\x03Get\x12\x12.kvs.v1.GetRequest\x1a\x13.kvs.v1.GetResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/kv/{key}\x12G\n" +
	"\x03Set\x12\x12.kvs.v1.SetRequest\x1a\x13.kvs.v1.SetResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\x1a\f/v1/kv/{key}\x12M\n" +
	"\x06Delete\x12\x15.kvs.v1.DeleteRequest\x1a\x16.kvs.v1.DeleteResponse\"\x14\x82\xd3\xe4\x93\x02\x0e*\f/v1/kv/{key}\x12O\n" +
	"\x05Watch\x12\x14.kvs.v1.WatchRequest\x1a\x15.kvs.v1.WatchResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/watch/{key}0\x01B1Z/github.com/davidaparicio/gokvs/api/kvs/v1;kvsv1b\x06proto3"

var (
	file_kvs_v1_kvs_proto_rawDescOnce sync.Once
	file_kvs_v1_kvs_proto_rawDescData []byte
)

func file_kvs_v1_kvs_proto_rawDescGZIP() []byte {
	file_kvs_v1_kvs_proto_rawDescOnce.Do(func() {
		file_kvs_v1_kvs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvs_v1_kvs_proto_rawDesc), len(file_kvs_v1_kvs_proto_rawDesc)))
	})
	return file_kvs_v1_kvs_proto_rawDescData
}

var file_kvs_v1_kvs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kvs_v1_kvs_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kvs_v1_kvs_proto_goTypes = []any{
	(EventType)(0),         // 0: kvs.v1.EventType
	(*GetRequest)(nil),     // 1: kvs.v1.GetRequest
	(*GetResponse)(nil),    // 2: kvs.v1.GetResponse
	(*SetRequest)(nil),     // 3: kvs.v1.SetRequest
	(*SetResponse)(nil),    // 4: kvs.v1.SetResponse
	(*DeleteRequest)(nil),  // 5: kvs.v1.DeleteRequest
	(*DeleteResponse)(nil), // 6: kvs.v1.DeleteResponse
	(*WatchRequest)(nil),   // 7: kvs.v1.WatchRequest
	(*WatchResponse)(nil),  // 8: kvs.v1.WatchResponse
}
var file_kvs_v1_kvs_proto_depIdxs = []int32{
	0, // 0: kvs.v1.WatchResponse.type:type_name -> kvs.v1.EventType
	1, // 1: kvs.v1.KVSService.Get:input_type -> kvs.v1.GetRequest
	3, // 2: kvs.v1.KVSService.Set:input_type -> kvs.v1.SetRequest
	5, // 3: kvs.v1.KVSService.Delete:input_type -> kvs.v1.DeleteRequest
	7, // 4: kvs.v1.KVSService.Watch:input_type -> kvs.v1.WatchRequest
	2, // 5: kvs.v1.KVSService.Get:output_type -> kvs.v1.GetResponse
	4, // 6: kvs.v1.KVSService.Set:output_type -> kvs.v1.SetResponse
	6, // 7: kvs.v1.KVSService.Delete:output_type -> kvs.v1.DeleteResponse
	8, // 8: kvs.v1.KVSService.Watch:output_type -> kvs.v1.WatchResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kvs_v1_kvs_proto_init() }
func file_kvs_v1_kvs_proto_init() {
	if File_kvs_v1_kvs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvs_v1_kvs_proto_rawDesc), len(file_kvs_v1_kvs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvs_v1_kvs_proto_goTypes,
		DependencyIndexes: file_kvs_v1_kvs_proto_depIdxs,
		EnumInfos:         file_kvs_v1_kvs_proto_enumTypes,
		MessageInfos:      file_kvs_v1_kvs_proto_msgTypes,
	}.Build()
	File_kvs_v1_kvs_proto = out.File
	file_kvs_v1_kvs_proto_goTypes = nil
	file_kvs_v1_kvs_proto_depIdxs = nil
}
