# This workflow runs benchmarks against the current branch, compares them to benchmarks against
# main, and uploads the results as an artifact. Unlike in the Validate workflow we only test these
# benchmarks against the latest versions of Go and the Runner.

name: Benchstat

on:
  workflow_call:

env:
  BENCH_COUNT: 10

jobs:
  benchstat:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Checkout incoming branch
        uses: actions/checkout@v6
      - name: Install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest
      - name: Benchmark incoming branch
        run: go test -run=XXX -bench=. -benchmem -count=${{ env.BENCH_COUNT }} ./... | tee bench-incoming.txt
      - name: Checkout baseline (main)
        uses: actions/checkout@v6
        with:
          ref: main
          clean: false
      - name: Benchmark baseline (main)
        run: go test -run=XXX -bench=. -benchmem -count=${{ env.BENCH_COUNT }} ./... | tee bench-baseline.txt
      - name: Benchstat Results
        run: |
          benchstat bench-baseline.txt bench-incoming.txt | tee benchstat.txt
          echo '## Benchstat Results' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat benchstat.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Upload benchmark results
        uses: actions/upload-artifact@v7
        with:
          name: benchstat
          path: |
            bench-incoming.txt
            bench-baseline.txt
            benchstat.txt
