# This workflow runs benchmarks against the current branch, compares them to benchmarks against
# main, and uploads the results as an artifact. Unlike in the Validate workflow we only test these
# benchmarks against the latest versions of Go and the Runner.

name: Benchstat

on:
  workflow_call:

env:
  BENCH_COUNT: 5

jobs:
  incoming:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          # go-version-file: go.mod
      - name: Checkout
        uses: actions/checkout@v6
      - name: Benchmark
        run: go test -run=XXX -bench=. -benchmem -count=${{ env.BENCH_COUNT }} ./... | tee bench.txt
      - name: Upload Benchmark
        uses: actions/upload-artifact@v7
        with:
          name: bench-incoming
          path: bench.txt
  baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          # go-version-file: go.mod
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
      - name: Benchmark
        run: go test -run=XXX -bench=. -benchmem -count=${{ env.BENCH_COUNT }} ./... | tee bench.txt
      - name: Upload Benchmark
        uses: actions/upload-artifact@v7
        with:
          name: bench-baseline
          path: bench.txt
  benchstat:
    needs: [incoming, baseline]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          # go-version-file: go.mod
      - name: Install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest
      - name: Download Incoming
        uses: actions/download-artifact@v8
        with:
          name: bench-incoming
          path: bench-incoming
      - name: Download Baseline
        uses: actions/download-artifact@v8
        with:
          name: bench-baseline
          path: bench-baseline
      - name: Benchstat Results
        run: |
          benchstat bench-baseline/bench.txt bench-incoming/bench.txt | tee benchstat.txt
          echo '## Benchstat Results' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat benchstat.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Upload benchstat results
        uses: actions/upload-artifact@v7
        with:
          name: benchstat
          path: benchstat.txt