name: Release (Docker)

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    strategy:
      matrix:
        os: [ubuntu-latest] #[macos-latest, ubuntu-latest, windows-latest]
    name: Build and Push
    #needs: [goreleaser] # sequential
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      #- 
      #  uses: docker-practice/actions-setup-docker@master
      #  if: ${{ matrix.os == 'macos-latest' }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push images to Docker Hub
        uses: docker/build-push-action@v4.1.1 #v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: user/app:latest
