name: "Security Scan (sonar)"

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every at 10:13 on Thursday UTC time.
# https://crontab.guru/#17_15_*_*_5
on:
  schedule:
    - cron: '17 15 * * 5'
  workflow_call:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@59db25f34e16620e48ab4bb9e4a5dce155cb5432 # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
# https://sonarcloud.io/project/configuration?id=davidaparicio_namecheck&analysisMode=GitHubActions
