name: "Security Scan (sonar)"

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every at 10:13 on Thursday UTC time.
# https://crontab.guru/#17_15_*_*_5
on:
  schedule:
    - cron: '17 15 * * 5'
  workflow_call:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
# https://sonarcloud.io/project/configuration?id=davidaparicio_namecheck&analysisMode=GitHubActions
