name: "Security Scan (sonar)"

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every at 10:13 on Thursday UTC time.
# https://crontab.guru/#17_15_*_*_5
on:
  schedule:
    - cron: '17 15 * * 5'
  workflow_call:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
# https://sonarcloud.io/project/configuration?id=davidaparicio_namecheck&analysisMode=GitHubActions
